[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crawl4ai>=0.7.4",
    "httpx>=0.28.1",
    "mcp[cli]>=1.17.0",
    "psycopg[binary]>=3.2.10",
    "sentence-transformers==2.7.0",
    "torch==2.5.1",
]
